# Generated by Django 4.2.2 on 2023-06-29 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id_promotion', models.AutoField(primary_key=True, serialize=False)),
                ('nom_promotion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_matricule', models.CharField(max_length=255, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse_email', models.CharField(max_length=255)),
                ('filiere', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('id_promotion', models.ForeignKey(db_column='id_promotion', on_delete=django.db.models.deletion.DO_NOTHING, to='timemanage.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Emploidutemps',
            fields=[
                ('id_emploi', models.AutoField(primary_key=True, serialize=False)),
                ('cours', models.CharField(max_length=100)),
                ('salle', models.CharField(max_length=100)),
                ('enseignant', models.CharField(max_length=100)),
                ('jour_semaine', models.CharField(max_length=20)),
                ('heure_debut', models.CharField(max_length=20)),
                ('heure_fin', models.CharField(max_length=20)),
                ('id_promotion', models.ForeignKey(db_column='id_promotion', on_delete=django.db.models.deletion.DO_NOTHING, to='timemanage.promotion')),
            ],
        ),
    ]
